---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/activities":
    get:
      summary: Retrieves all activities
      tags:
      - Activities
      security:
      - Bearer: {}
      responses:
        '200':
          description: activities found
    post:
      summary: Creates an activity
      tags:
      - Activities
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: activity created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/activity"
  "/api/v1/activities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    put:
      summary: Updates an activity
      tags:
      - Activities
      security:
      - Bearer: {}
      parameters: []
      responses:
        '200':
          description: activity updated
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/activity"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      description: Bearer Token
      type: apiKey
      name: Authorization
      in: header
  schemas:
    activity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        date:
          type: string
          format: date
        start_time:
          type: string
          format: full-time
        finish_time:
          type: string
          format: full-time
        category:
          type: object
      required:
      - id
      - name
      - date
      - start_time
      - finish_time
