---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/activities":
    get:
      summary: Retrieves all activities
      tags:
      - Activities
      responses:
        '200':
          description: activities found
    post:
      summary: Creates a activity
      tags:
      - Activities
      parameters: []
      responses:
        '201':
          description: activity created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                date:
                  type: string
                start_time:
                  type: string
                finish_time:
                  type: string
                category:
                  type: object
              required:
              - name
              - date
              - start_time
              - finish_time
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    activity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        date:
          type: string
          format: date
        start_time:
          type: string
          format: full-time
        finish_time:
          type: string
          format: full-time
        category:
          type: object
      required:
      - id
      - name
      - date
      - start_time
      - finish_time
